runtime: nodejs10

#XXX DEV ONLY
# default_expiration: 1m

automatic_scaling:
  max_instances: 1

handlers:
- url: /$
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301
- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto
- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  redirect_http_response_code: 301
